/**
 * Writes the compiled MaterialRegistry ABI and creation bytecode into the API
 * package, so the API image can deploy the registry itself (the demo host has
 * no Hardhat or Solidity compiler).
 *
 *   pnpm --filter @trace/contracts compile
 *   pnpm --filter @trace/contracts export:api-artifacts
 *
 * test/ApiArtifacts.test.ts fails whenever the exported file no longer matches
 * a fresh compile, so the bundled bytecode can never drift from the source.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as prettier from 'prettier';

export const API_ARTIFACT_PATH = path.join(
  __dirname,
  '..',
  '..',
  'api',
  'src',
  'lib',
  'chain',
  'artifacts',
  'material-registry.ts',
);

export async function renderApiArtifact(artifact: {
  abi: unknown[];
  bytecode: string;
}): Promise<string> {
  // Formatted with the repository's own Prettier config so the committed file
  // passes `pnpm format:check` and the drift test compares like with like.
  const options = (await prettier.resolveConfig(API_ARTIFACT_PATH)) ?? {};
  const source = `// GENERATED by packages/contracts/scripts/export-api-artifacts.ts — do not edit.
// Compiled MaterialRegistry (solc 0.8.20, evmVersion paris, optimizer 200 runs).
// test/ApiArtifacts.test.ts in @trace/contracts fails if this drifts from the source.

export const MATERIAL_REGISTRY_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;

export const MATERIAL_REGISTRY_BYTECODE =
  '${artifact.bytecode}';
`;
  return prettier.format(source, { ...options, filepath: API_ARTIFACT_PATH });
}

async function main(): Promise<void> {
  const artifactPath = path.join(
    __dirname,
    '..',
    'artifacts',
    'contracts',
    'MaterialRegistry.sol',
    'MaterialRegistry.json',
  );
  if (!fs.existsSync(artifactPath)) {
    throw new Error(
      `Missing ${artifactPath}; run \`pnpm --filter @trace/contracts compile\` first`,
    );
  }
  const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8')) as {
    abi: unknown[];
    bytecode: string;
  };
  fs.mkdirSync(path.dirname(API_ARTIFACT_PATH), { recursive: true });
  fs.writeFileSync(API_ARTIFACT_PATH, await renderApiArtifact(artifact));
  console.log(`Wrote ${path.relative(process.cwd(), API_ARTIFACT_PATH)}`);
}

if (require.main === module) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
  });
}
